# Site settings
title       : Skate or Bike
description : Sometimes we ride 4, sometimes we ride 2.
url         : https://skateorbike.com/
twitter     : skateorbike
creator     : huphtur
image       : images/favicons/android-chrome-512x512.png

# Build settings
markdown            : kramdown
kramdown:
  input             : GFM
  auto_ids          : true
  auto_id_stripping : true
permalink           : /:title/
exclude             : [CNAME]
sass:
  style             : expanded
  deploy_style      : compressed
