# Site settings
title       : Skate or Bike
description : Sometimes we ride 4, sometimes we ride 2.
url         : https://skateorbike.com/

# Build settings
excerpt_separator : <!--more-->
markdown          : kramdown
highlighter       : rouge
kramdown          :
  input           : GFM
permalink         : /:title/
exclude           : [CNAME]

sass:
style       : expanded
deploy_style: compressed
